pipeline {
    agent any

    stages {

        stage('Code checkout according to environment') {
            steps {
                script{
                  checkout changelog: false, poll: false, scm: scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'gtihub-credentials', url: 'https://github.com/Advaita-Amit25/DevOps-Assignment.git']])
                }
            }
        }
        stage("Build the code"){
            steps{
              sh "cd ./DevOpsDemo"
              sh "chmod +x ./mvnw"
              sh "./mvnw clean package"

            }
        }


        stage('create image for docker') {
            steps{
              sh "cd ./DevOpsDemo"
              sh 'docker build -t spring:myApp .'
            }
        }

        stage('Run the container'){
            steps{
              sh "cd ./DevOpsDemo"
              sh 'docker run -p 5500:8090 spring:myApp'
            }
        }
    }
}